/**
 * Created by lenovo on 2015/12/16.
 */
({
    mainConfigFile:'main.js',
    baseUrl:'../app',
    paths:{
        jquery:'lib/jquery',
        //index:'components/generator/index',
        angular:'lib/angular',
        uiRouter:'lib/angular-ui-router',
        zui:'lib/zui',
        msgBox:'lib/msg.hint'
    },
    shim:{
        'angular':{
            'exports':'angular'
        },
        'uiRouter':{
            deps:['angular']
            // exports:'uiRouter'
        },
        zui:{
            deps:['jquery'],
            exports:'zui'
        },
        msgBox:{
            deps:['zui'],
            exports:'msgBox'
        }
    },
    fileExclusiongRegExp:/^(r|build)\.js|.*\.scss$|^(bower|node)/,
    //excludeShallow:["angular","jquery"],
    name:'main',
    out:'main-built.js'
})